name: Wealthfolio
slug: wealthfolio
version: "0.1.0"
description: Home Assistant add-on per Wealthfolio
url: "https://github.com/robertodigisi/ha-addon-wealthfolio/tree/main/wealthfolio"
arch:
  - amd64
init: false
map:
  - share:rw
volumes:
  - /config/wealthfolio:/data
environment:
  WF_DB_PATH: "/data/wealthfolio.db"
  WF_SECRET_KEY: "CHANGE_ME"
image: afadil/wealthfolio"
options: {}
schema: {}
